management:
  endpoints:
    web:
      exposure:
        include: "*"
      ## \u81EA\u5B9A\u4E49\u670D\u52A1\u5730\u5740
      base-path: /monitor
  ## \u589E\u52A0post\u505C\u673A\u7684\u529F\u80FD
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

  server:
    ## \u81EA\u5B9A\u4E49\u7AEF\u53E3
    port: 9999

## \u589E\u52A0\u8FDB\u5165\u76D1\u63A7\u754C\u9762\u7684\u767B\u5F55\u6743\u9650
spring:
  security:
    user:
      name: admin
      password: admin
