logging:
  level:
    com.duyi: TRACE
spring:
  redis:
    host: www.desolator.cn
    port: 7790
    password: slave
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 1